version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - app-network

  my-app:
    image: vishwatech/milkhub:latest
    container_name: my-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
