version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    env_file:
      - .env
    ports:
      - "3000:3000"

    environment:
      - NODE_ENV=production
      - REDIS_URL_PROD=redis://redis:6379
      - REDIS_URL_DEV=redis://redis:6379
    networks:
      - app-network
    depends_on:
      - mongo
      - redis

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
