name: Deploy Next.js application
on:
  push:
    branches:  
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env && echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
      - name: Build docker image
        run: docker build -t vishwatech/dairymaster .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to docker hub
        run: docker push vishwatech/dairymaster:latest
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull images from docker hub
        run: docker pull vishwatech/dairymaster:latest
      - name: Delete old container
        run: docker rm -f dairymaster-container || true  # Removes the container if it exists

      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name dairymaster-container vishwatech/dairymaster:latest
